### Arithmetic operations

We will first see the basic arithmetic operations in R. The following operators stand for:

|Operator|Description|
|--------|-----------|
|+|Addition|
|-|Subtraction|
|*|Multiplication|
|/|Division|
|^|or| 
|**|Exponentiation|

In [13]:
# An addition
3 + 4

[1] 7

In [14]:
# A multiplication
3*5

[1] 15

In [21]:
# A division
(5+5)/2

[1] 5

In [22]:
28/6

[1] 4.666667

In [18]:
# Exponentiation
2^5

[1] 32

In [31]:
# Modulo
28%%6

[1] 4

##### Vectors On Arthmatical Operations

In [24]:
x <- c(2,8,3)
y <- c(6,4,1)
x+y

[1]  8 12  4

In [26]:
x-y

[1] -4  4  2

In [28]:
x*y

[1] 12 32  3

In [30]:
x/y

[1] 0.3333333 2.0000000 3.0000000

In [33]:
x%%y

[1] 2 0 0

In [35]:
x**y

[1]   64 4096    3

#### Matrix for Arthmatical operations

In [51]:
a <- matrix(c(1:12),nrow=4,ncol=3)
b <- matrix(c(12:23),nrow=4,ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [53]:
print(b)

     [,1] [,2] [,3]
[1,]   12   16   20
[2,]   13   17   21
[3,]   14   18   22
[4,]   15   19   23


In [55]:
a+b

[,1] [,2] [,3]
[1,] 13   21   29  
[2,] 15   23   31  
[3,] 17   25   33  
[4,] 19   27   35

In [57]:
a-b

[,1] [,2] [,3]
[1,] -11  -11  -11 
[2,] -11  -11  -11 
[3,] -11  -11  -11 
[4,] -11  -11  -11

In [59]:
a*b

[,1] [,2] [,3]
[1,] 12    80  180 
[2,] 26   102  210 
[3,] 42   126  242 
[4,] 60   152  276

In [61]:
a/b

[,1]       [,2]      [,3]     
[1,] 0.08333333 0.3125000 0.4500000
[2,] 0.15384615 0.3529412 0.4761905
[3,] 0.21428571 0.3888889 0.5000000
[4,] 0.26666667 0.4210526 0.5217391

In [63]:
a%%b

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [65]:
a**b

[,1]       [,2]         [,3]        
[1,]          1 1.525879e+11 1.215767e+19
[2,]       8192 1.692666e+13 1.000000e+21
[3,]    4782969 1.628414e+15 8.140275e+22
[4,] 1073741824 1.441152e+17 6.624737e+24

In [66]:
a^b

[,1]       [,2]         [,3]        
[1,]          1 1.525879e+11 1.215767e+19
[2,]       8192 1.692666e+13 1.000000e+21
[3,]    4782969 1.628414e+15 8.140275e+22
[4,] 1073741824 1.441152e+17 6.624737e+24

**Comparing Operators**

|Operator|Description|
|--------|-----------|
|<	|Less than|
|>	|Greater than|
|<=	|Less than or equal to|
|>=	|Greater than or equal to|
|==	|Equal to|
|!=	|Not equal to|

In [69]:
x

[1] 2 8 3

In [70]:
y

[1] 6 4 1

In [67]:
x>y

[1] FALSE  TRUE  TRUE

In [72]:
x<y

[1]  TRUE FALSE FALSE

In [74]:
x<=y

[1]  TRUE FALSE FALSE

In [76]:
x>=y

[1] FALSE  TRUE  TRUE

In [78]:
x!=y

[1] TRUE TRUE TRUE

In [84]:
11==10

[1] FALSE

In [85]:
# Create a vector from 1 to 10
logical_vector <- c(1:10)
logical_vector>5

[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

In [86]:
# Print value strictly above 5
logical_vector[(logical_vector>5)]

[1]  6  7  8  9 10

In [91]:
# Print 5 and 6
logical_vector <- c(1:10)
logical_vector[(logical_vector>4) == (logical_vector<7)]


[1] 5 6

In [97]:
print(a) ; print(b)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
     [,1] [,2] [,3]
[1,]   12   16   20
[2,]   13   17   21
[3,]   14   18   22
[4,]   15   19   23


In [108]:
a>b 

[,1]  [,2]  [,3] 
[1,] FALSE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE FALSE FALSE
[4,] FALSE FALSE FALSE

In [109]:
a>=b

[,1]  [,2]  [,3] 
[1,] FALSE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE FALSE FALSE
[4,] FALSE FALSE FALSE

In [106]:
a<b

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE
[3,] TRUE TRUE TRUE
[4,] TRUE TRUE TRUE

In [107]:
a<=b

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE
[3,] TRUE TRUE TRUE
[4,] TRUE TRUE TRUE

In [104]:
a!=b

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE
[3,] TRUE TRUE TRUE
[4,] TRUE TRUE TRUE

In [105]:
a==b

[,1]  [,2]  [,3] 
[1,] FALSE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE FALSE FALSE
[4,] FALSE FALSE FALSE

### R Logical Operators

Logical operators are used to carry out Boolean operations like AND, OR etc.


|Operator	|Description|
|-----------|-----------|
|!	|Logical NOT||
|&	|Element-wise logical AND|
|&&	|Logical AND|
||	|Element-wise logical OR|
|`||`|Logical OR|

In [135]:
x <- FALSE
y <- FALSE

In [136]:
x & y

[1] FALSE

In [137]:
x && y

[1] FALSE

In [138]:
!x

[1] TRUE

In [139]:
x | y

[1] FALSE

In [140]:
x || y

[1] FALSE

Operators & and | perform element-wise operation producing result having length of the longer operand.

But && and || examines only the first element of the operands resulting into a single length logical vector.

In [149]:
x <- c(TRUE,FALSE,0,6)
y <- c(FALSE,TRUE,FALSE,TRUE)

In [150]:
!x

[1] FALSE  TRUE  TRUE FALSE

In [146]:
!y

[1]  TRUE FALSE  TRUE FALSE

In [151]:
x & y

[1] FALSE FALSE FALSE  TRUE

In [152]:
x| y 

[1]  TRUE  TRUE FALSE  TRUE

In [153]:
x && y 

[1] FALSE

In [154]:
x || y

[1] TRUE

## R Assignment Operators
These operators are used to assign values to variables.

|Operator|	Description|
|---------|------------|
|<-, <<-, =	|Leftwards assignment|
|->, ->>	|Rightwards assignment|

In [1]:
x <- 5
x

[1] 5

In [2]:
x = 9
x

[1] 9

In [3]:
10 -> x
x

[1] 10

In [5]:
x <- c(1,2,3)
y <- c(5,4,3)
x+y

[1] 6 6 6

In [7]:
x<- list(10,20,30,40,50)
x

[[1]]
[1] 10

[[2]]
[1] 20

[[3]]
[1] 30

[[4]]
[1] 40

[[5]]
[1] 50

In [11]:
y<-list(2,60,50,20,20)
y

[[1]]
[1] 2

[[2]]
[1] 60

[[3]]
[1] 50

[[4]]
[1] 20

[[5]]
[1] 20

In [12]:
x+y

ERROR: Error in x + y: non-numeric argument to binary operator


#### Take a User input

In [13]:
my.name <- readline(prompt="Enter name: ")
print(my.name)

Enter name: R Program
[1] "R Program"


In [15]:
my.name <- readline(prompt="Enter name: ")
my.age <- readline(prompt="Enter age: ")
my.Gender <- readline(prompt="Enter Gender: ")
# convert character into integer
my.age <- as.integer(my.age)

Enter name: Reddy
Enter age: 27
Enter Gender: M


In [16]:
print(paste("Hi,", my.name, "next year you will be", my.age+1, "years old, Your Gender is,",my.Gender))

[1] "Hi, Reddy next year you will be 28 years old, Your Gender is, M"


###  Type Casting 
Converting The Data one Form to another.

In [19]:
a <- c(10,20,30,40,50,60,70,80)
a

[1] 10 20 30 40 50 60 70 80

In [20]:
as.factor(a)

[1] 10 20 30 40 50 60 70 80
Levels: 10 20 30 40 50 60 70 80

In [24]:
as.integer(a)

[1] 10 20 30 40 50 60 70 80

In [25]:
as.array(a)

[1] 10 20 30 40 50 60 70 80

In [22]:
as.complex(a)

[1] 10+0i 20+0i 30+0i 40+0i 50+0i 60+0i 70+0i 80+0i

In [26]:
as.matrix(a)

[,1]
[1,] 10  
[2,] 20  
[3,] 30  
[4,] 40  
[5,] 50  
[6,] 60  
[7,] 70  
[8,] 80

In [27]:
as.list(a)

[[1]]
[1] 10

[[2]]
[1] 20

[[3]]
[1] 30

[[4]]
[1] 40

[[5]]
[1] 50

[[6]]
[1] 60

[[7]]
[1] 70

[[8]]
[1] 80

In [34]:
b = c(10.5,20.5,30.5,40.5,50.5,60.5,70.5,80.5)
as.data.frame(a)+as.data.frame(b)

a    
1  20.5
2  40.5
3  60.5
4  80.5
5 100.5
6 120.5
7 140.5
8 160.5

In [43]:
Gender<-c(rep("Male",20), rep("Female",30),rep("Other",5))
Gender<-factor(Gender)
Gender

[1] Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  
[11] Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  
[21] Female Female Female Female Female Female Female Female Female Female
[31] Female Female Female Female Female Female Female Female Female Female
[41] Female Female Female Female Female Female Female Female Female Female
[51] Other  Other  Other  Other  Other 
Levels: Female Male Other

In [45]:
summary(Gender)

Female   Male  Other 
    30     20      5

In [50]:
rating <- c(rep('Large',10),rep('Medium',20),rep('Small',5))
rating<-ordered(rating)
rating

[1] Large  Large  Large  Large  Large  Large  Large  Large  Large  Large 
[11] Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium
[21] Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium
[31] Small  Small  Small  Small  Small 
Levels: Large < Medium < Small

In [52]:
summary(rating)

Large Medium  Small 
    10     20      5

<div class="alert alert-block alert-warning">
<b>Built In Funcation</b> Usefull Funcation.
</div>

In [54]:
length(objects)

[1] 1

In [57]:
str(rating)

 Ord.factor w/ 3 levels "Large"<"Medium"<..: 1 1 1 1 1 1 1 1 1 1 ...


In [59]:
class(rating)

[1] "ordered" "factor"

In [61]:
names(rating)

NULL

In [64]:
M1<-matrix(1:12,nrow = 4,ncol = 3)
M1

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [68]:
M2<-matrix(12:23,nrow=4,ncol=3)
M2

[,1] [,2] [,3]
[1,] 12   16   20  
[2,] 13   17   21  
[3,] 14   18   22  
[4,] 15   19   23

In [70]:
cbind(M1,M2)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    5     9   12   16   20  
[2,] 2    6    10   13   17   21  
[3,] 3    7    11   14   18   22  
[4,] 4    8    12   15   19   23

In [75]:
rbind(M1,M2)

[,1] [,2] [,3]
[1,]  1    5    9  
[2,]  2    6   10  
[3,]  3    7   11  
[4,]  4    8   12  
[5,] 12   16   20  
[6,] 13   17   21  
[7,] 14   18   22  
[8,] 15   19   23

In [77]:
ls()

[1] "a"         "b"         "Gender"    "M1"        "M2"        "my.age"   
 [7] "my.Gender" "my.name"   "rating"    "x"         "y"

In [78]:
c(M1,M2)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 12 13 14 15 16 17 18 19 20 21 22 23

In [82]:
rm(b)

In [83]:
ls()

[1] "Gender"    "M1"        "M2"        "my.age"    "my.Gender" "my.name"  
[7] "rating"    "x"         "y"